FROM openjdk:8-jdk-alpine

# Add Maintainer info:
MAINTAINER GA <admin@xyz.com>

# Add a volume pointing to /tmp:
VOLUME /tmp

# Make port 80 available to the world outside this container:
EXPOSE 8083

# The application's JAR file:
ARG JAR_FILE=target/comments-api-0.0.1-SNAPSHOT.jar

# Add the application's JAR to the container:
ADD ${JAR_FILE} comments-api.jar

ENV SPRING_PROFILES_ACTIVE dev

COPY ./src/main/resources/*.properties /config/
COPY ./src/main/resources/*.yml /config/

# Run the jar file:
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/comments-api.jar"]
